version: '3.1'

services:

  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=vwl-chatbot
      - MONGO_INITDB_ROOT_PASSWORD=monopolytask
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db


volumes:
  mongodb:
    driver: local